// Professional ID Card Design Templates
export const DEFAULT_TEMPLATES = [
  {
    id: 'student-campus',
    name: 'Academic Campus ID',
    category: 'Student',
    orientation: 'landscape',
    front: {
      background: {
        type: 'gradient',
        color: '#f8fafc',
        gradientStart: '#ffffff',
        gradientEnd: '#f1f5f9',
        opacity: 1
      },
      elements: [
        // Top Header bar
        {
          id: 'elem-header-bar',
          name: 'Header Banner',
          type: 'shape',
          shapeType: 'rect',
          x: 0,
          y: 0,
          width: 640,
          height: 80,
          fill: '#1e40af',
          stroke: '',
          strokeWidth: 0,
          cornerRadius: 0,
          opacity: 1,
          locked: false,
          visible: true
        },
        // College Name text
        {
          id: 'elem-inst-name',
          name: 'Institution Name',
          type: 'text',
          text: '{{company_name}}',
          fontSize: 18,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: 'bold',
          fill: '#ffffff',
          align: 'left',
          x: 24,
          y: 20,
          width: 440,
          height: 26,
          letterSpacing: 0.5,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Tagline / Subtitle
        {
          id: 'elem-inst-sub',
          name: 'Tagline',
          type: 'text',
          text: 'STUDENT IDENTITY CREDENTIAL • 2023-2027',
          fontSize: 10,
          fontFamily: 'JetBrains Mono',
          fontWeight: '600',
          fill: '#93c5fd',
          align: 'left',
          x: 24,
          y: 48,
          width: 400,
          height: 18,
          letterSpacing: 1,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Photo Holder Border / Box
        {
          id: 'elem-photo-bg',
          name: 'Photo Frame',
          type: 'shape',
          shapeType: 'rounded-rect',
          x: 30,
          y: 110,
          width: 140,
          height: 165,
          fill: '#e2e8f0',
          stroke: '#cbd5e1',
          strokeWidth: 2,
          cornerRadius: 12,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Profile Photo element
        {
          id: 'elem-profile-photo',
          name: 'Student Photo',
          type: 'image',
          src: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
          x: 32,
          y: 112,
          width: 136,
          height: 161,
          clipType: 'rounded',
          cornerRadius: 10,
          borderWidth: 0,
          borderColor: '#ffffff',
          opacity: 1,
          locked: false,
          visible: true
        },
        // Student Name
        {
          id: 'elem-student-name',
          name: 'Full Name',
          type: 'text',
          text: '{{name}}',
          fontSize: 22,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '800',
          fill: '#0f172a',
          align: 'left',
          x: 195,
          y: 110,
          width: 320,
          height: 32,
          letterSpacing: 0,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Roll / ID Number
        {
          id: 'elem-id-badge',
          name: 'ID Number',
          type: 'text',
          text: 'ROLL NO: {{employee_id}}',
          fontSize: 13,
          fontFamily: 'JetBrains Mono',
          fontWeight: 'bold',
          fill: '#2563eb',
          align: 'left',
          x: 195,
          y: 146,
          width: 300,
          height: 22,
          letterSpacing: 0.5,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Department / Branch
        {
          id: 'elem-dept',
          name: 'Department',
          type: 'text',
          text: 'DEPT: {{department}}',
          fontSize: 12,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '600',
          fill: '#475569',
          align: 'left',
          x: 195,
          y: 178,
          width: 300,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Designation / Year
        {
          id: 'elem-year',
          name: 'Academic Year',
          type: 'text',
          text: 'YEAR: {{designation}}',
          fontSize: 12,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '500',
          fill: '#64748b',
          align: 'left',
          x: 195,
          y: 204,
          width: 300,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Blood Group
        {
          id: 'elem-blood-group',
          name: 'Blood Group',
          type: 'text',
          text: 'BLOOD: {{bloodGroup}}',
          fontSize: 12,
          fontFamily: 'JetBrains Mono',
          fontWeight: 'bold',
          fill: '#dc2626',
          align: 'left',
          x: 195,
          y: 230,
          width: 200,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // QR Code in bottom right
        {
          id: 'elem-qr-code',
          name: 'Verification QR',
          type: 'qr',
          value: 'https://verify.auntyid.com/student/{{employee_id}}',
          x: 520,
          y: 110,
          width: 90,
          height: 90,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Bottom Accent Divider Line
        {
          id: 'elem-footer-accent',
          name: 'Accent Line',
          type: 'shape',
          shapeType: 'line',
          x: 0,
          y: 360,
          width: 640,
          height: 4,
          fill: '#3b82f6',
          stroke: '#3b82f6',
          strokeWidth: 4,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Emergency / Validity strip
        {
          id: 'elem-validity-strip',
          name: 'Validity Note',
          type: 'text',
          text: 'VALID THRU: {{expiry_date}} • PH: {{phone}}',
          fontSize: 10,
          fontFamily: 'JetBrains Mono',
          fontWeight: '500',
          fill: '#64748b',
          align: 'left',
          x: 30,
          y: 374,
          width: 580,
          height: 18,
          opacity: 1,
          locked: false,
          visible: true
        }
      ]
    },
    back: {
      background: {
        type: 'solid',
        color: '#ffffff',
        opacity: 1
      },
      elements: [
        // Back Header
        {
          id: 'elem-back-header',
          name: 'Rules Header',
          type: 'text',
          text: 'TERMS & INSTRUCTIONS',
          fontSize: 13,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '800',
          fill: '#1e40af',
          align: 'left',
          x: 30,
          y: 24,
          width: 300,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Terms Body
        {
          id: 'elem-back-rules',
          name: 'Instructions Text',
          type: 'text',
          text: '1. This card is non-transferable and remains property of {{company_name}}.\n2. In case of loss, report immediately to the campus security office.\n3. Display this card upon request when accessing labs, library, or campus gates.',
          fontSize: 11,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: 'normal',
          fill: '#475569',
          align: 'left',
          x: 30,
          y: 54,
          width: 580,
          height: 70,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Campus Address
        {
          id: 'elem-back-address',
          name: 'Campus Address',
          type: 'text',
          text: 'CAMPUS ADDRESS: {{address}}',
          fontSize: 10,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '600',
          fill: '#64748b',
          align: 'left',
          x: 30,
          y: 150,
          width: 580,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Emergency Phone
        {
          id: 'elem-back-phone',
          name: 'Emergency Contact',
          type: 'text',
          text: 'EMERGENCY HELPLINE: {{phone}} | EMAIL: {{email}}',
          fontSize: 10,
          fontFamily: 'JetBrains Mono',
          fontWeight: '600',
          fill: '#1e40af',
          align: 'left',
          x: 30,
          y: 180,
          width: 580,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Barcode
        {
          id: 'elem-back-barcode',
          name: 'Access Barcode',
          type: 'barcode',
          value: '{{employee_id}}',
          x: 180,
          y: 240,
          width: 280,
          height: 65,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Signature Line
        {
          id: 'elem-back-sig-line',
          name: 'Signature Line',
          type: 'shape',
          shapeType: 'line',
          x: 430,
          y: 350,
          width: 170,
          height: 1,
          fill: '#94a3b8',
          stroke: '#94a3b8',
          strokeWidth: 1,
          opacity: 1,
          locked: false,
          visible: true
        },
        {
          id: 'elem-back-sig-label',
          name: 'Signature Label',
          type: 'text',
          text: 'AUTHORIZED REGISTRAR',
          fontSize: 9,
          fontFamily: 'JetBrains Mono',
          fontWeight: 'bold',
          fill: '#94a3b8',
          align: 'center',
          x: 430,
          y: 358,
          width: 170,
          height: 16,
          opacity: 1,
          locked: false,
          visible: true
        }
      ]
    }
  },
  {
    id: 'corporate-minimal',
    name: 'Corporate Executive Badge',
    category: 'Corporate',
    orientation: 'landscape',
    front: {
      background: {
        type: 'solid',
        color: '#0f172a',
        opacity: 1
      },
      elements: [
        // Left Color Splash Panel
        {
          id: 'elem-corp-panel',
          name: 'Accent Panel',
          type: 'shape',
          shapeType: 'rect',
          x: 0,
          y: 0,
          width: 12,
          height: 404,
          fill: '#06b6d4',
          stroke: '',
          strokeWidth: 0,
          cornerRadius: 0,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Company Name
        {
          id: 'elem-corp-name',
          name: 'Company Header',
          type: 'text',
          text: '{{company_name}}',
          fontSize: 16,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: 'bold',
          fill: '#06b6d4',
          align: 'left',
          x: 36,
          y: 30,
          width: 400,
          height: 24,
          letterSpacing: 1,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Profile Photo
        {
          id: 'elem-corp-photo',
          name: 'Employee Photo',
          type: 'image',
          src: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
          x: 36,
          y: 80,
          width: 130,
          height: 160,
          clipType: 'rounded',
          cornerRadius: 8,
          borderWidth: 2,
          borderColor: '#334155',
          opacity: 1,
          locked: false,
          visible: true
        },
        // Name
        {
          id: 'elem-corp-emp-name',
          name: 'Employee Name',
          type: 'text',
          text: '{{name}}',
          fontSize: 24,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '800',
          fill: '#ffffff',
          align: 'left',
          x: 190,
          y: 84,
          width: 320,
          height: 32,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Designation
        {
          id: 'elem-corp-desig',
          name: 'Role / Designation',
          type: 'text',
          text: '{{designation}}',
          fontSize: 14,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '600',
          fill: '#94a3b8',
          align: 'left',
          x: 190,
          y: 122,
          width: 320,
          height: 22,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Badge ID
        {
          id: 'elem-corp-badge-id',
          name: 'Staff ID',
          type: 'text',
          text: 'EMPLOYEE ID: {{employee_id}}',
          fontSize: 12,
          fontFamily: 'JetBrains Mono',
          fontWeight: 'bold',
          fill: '#06b6d4',
          align: 'left',
          x: 190,
          y: 160,
          width: 300,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // Department
        {
          id: 'elem-corp-dept',
          name: 'Department',
          type: 'text',
          text: 'DEPARTMENT: {{department}}',
          fontSize: 11,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: '500',
          fill: '#64748b',
          align: 'left',
          x: 190,
          y: 188,
          width: 300,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        // QR Code
        {
          id: 'elem-corp-qr',
          name: 'Security QR',
          type: 'qr',
          value: 'https://security.company.com/verify/{{employee_id}}',
          x: 520,
          y: 80,
          width: 90,
          height: 90,
          opacity: 1,
          locked: false,
          visible: true
        }
      ]
    },
    back: {
      background: {
        type: 'solid',
        color: '#1e293b',
        opacity: 1
      },
      elements: [
        {
          id: 'elem-corp-back-title',
          name: 'Company Address Title',
          type: 'text',
          text: 'GLOBAL HEADQUARTERS',
          fontSize: 12,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: 'bold',
          fill: '#06b6d4',
          align: 'left',
          x: 36,
          y: 30,
          width: 300,
          height: 20,
          opacity: 1,
          locked: false,
          visible: true
        },
        {
          id: 'elem-corp-back-address',
          name: 'Office Address',
          type: 'text',
          text: '{{address}}\nPhone: {{phone}}\nSupport: {{email}}',
          fontSize: 11,
          fontFamily: 'Plus Jakarta Sans',
          fontWeight: 'normal',
          fill: '#cbd5e1',
          align: 'left',
          x: 36,
          y: 60,
          width: 500,
          height: 60,
          opacity: 1,
          locked: false,
          visible: true
        },
        {
          id: 'elem-corp-back-barcode',
          name: 'Asset Barcode',
          type: 'barcode',
          value: '{{employee_id}}',
          x: 160,
          y: 200,
          width: 320,
          height: 70,
          opacity: 1,
          locked: false,
          visible: true
        }
      ]
    }
  }
];
