/**
 * Default design state for Horizontal (600x380) and Vertical (380x600) ID Cards.
 * All coordinates and dimensions are in virtual canvas pixels.
 */

export const CANVAS_DIMENSIONS = {
  horizontal: { width: 600, height: 380 },
  vertical: { width: 380, height: 600 }
};

export const DEFAULT_HORIZONTAL_DESIGN = {
  card: {
    orientation: 'horizontal',
    background: '#ffffff',
    headerBg: 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 60%, #1d4ed8 100%)',
    borderRadius: 18,
    borderColor: '#93c5fd',
    borderWidth: 1,
    accentColor: '#38bdf8',
    themeId: 'oxford-blue'
  },
  elements: {
    // Top Header Elements
    collegeEmblem: {
      id: 'collegeEmblem',
      label: 'College Emblem',
      type: 'icon',
      x: 24,
      y: 16,
      width: 42,
      height: 42,
      rotation: 0,
      visible: true,
      zIndex: 20
    },
    collegeName: {
      id: 'collegeName',
      label: 'College Name',
      type: 'text',
      x: 76,
      y: 16,
      width: 440,
      height: 24,
      fontSize: 16,
      fontWeight: '800',
      color: '#ffffff',
      rotation: 0,
      visible: true,
      zIndex: 20,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    collegeTagline: {
      id: 'collegeTagline',
      label: 'Institution Tagline',
      type: 'text',
      x: 76,
      y: 40,
      width: 400,
      height: 18,
      fontSize: 9,
      fontWeight: '600',
      color: '#93c5fd',
      rotation: 0,
      visible: true,
      zIndex: 20,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    smartChip: {
      id: 'smartChip',
      label: 'Smart Chip',
      type: 'object',
      x: 532,
      y: 18,
      width: 38,
      height: 28,
      rotation: 0,
      visible: true,
      zIndex: 20
    },
    idRibbon: {
      id: 'idRibbon',
      label: 'Student ID Ribbon',
      type: 'badge',
      x: 0,
      y: 70,
      width: 600,
      height: 24,
      fontSize: 10,
      fontWeight: '700',
      color: '#ffffff',
      rotation: 0,
      visible: true,
      zIndex: 16
    },

    // Body: Left Photo
    studentPhoto: {
      id: 'studentPhoto',
      label: 'Student Photo',
      type: 'image',
      x: 28,
      y: 110,
      width: 120,
      height: 140,
      rotation: 0,
      visible: true,
      zIndex: 15,
      shape: 'square',
      borderColor: '#38bdf8',
      borderWidth: 2
    },

    // Body: Middle Details
    studentName: {
      id: 'studentName',
      label: 'Student Name',
      type: 'text',
      x: 170,
      y: 110,
      width: 270,
      height: 32,
      fontSize: 20,
      fontWeight: '900',
      color: '#0f172a',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    rollNumber: {
      id: 'rollNumber',
      label: 'Roll Number',
      type: 'badge',
      x: 170,
      y: 146,
      width: 200,
      height: 24,
      fontSize: 11,
      fontWeight: '700',
      color: '#1e40af',
      rotation: 0,
      visible: true,
      zIndex: 15
    },
    branch: {
      id: 'branch',
      label: 'Branch / Major',
      type: 'text',
      x: 170,
      y: 178,
      width: 270,
      height: 22,
      fontSize: 12,
      fontWeight: '700',
      color: '#1e3a8a',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    yearSection: {
      id: 'yearSection',
      label: 'Year & Section',
      type: 'text',
      x: 170,
      y: 204,
      width: 270,
      height: 20,
      fontSize: 11,
      fontWeight: '600',
      color: '#475569',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    email: {
      id: 'email',
      label: 'Email',
      type: 'text',
      x: 170,
      y: 228,
      width: 270,
      height: 20,
      fontSize: 11,
      fontWeight: '500',
      color: '#334155',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    phone: {
      id: 'phone',
      label: 'Phone Number',
      type: 'text',
      x: 170,
      y: 250,
      width: 270,
      height: 20,
      fontSize: 11,
      fontWeight: '500',
      color: '#334155',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    bloodGroup: {
      id: 'bloodGroup',
      label: 'Blood Group',
      type: 'text',
      x: 170,
      y: 274,
      width: 140,
      height: 20,
      fontSize: 11,
      fontWeight: '700',
      color: '#e11d48',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    dob: {
      id: 'dob',
      label: 'Date of Birth',
      type: 'text',
      x: 290,
      y: 274,
      width: 150,
      height: 20,
      fontSize: 11,
      fontWeight: '500',
      color: '#475569',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    address: {
      id: 'address',
      label: 'Address',
      type: 'text',
      x: 28,
      y: 310,
      width: 380,
      height: 24,
      fontSize: 10,
      fontWeight: '500',
      color: '#64748b',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },

    // Body: Right QR & Signature
    qrCode: {
      id: 'qrCode',
      label: 'QR Code',
      type: 'qr',
      x: 480,
      y: 115,
      width: 85,
      height: 85,
      rotation: 0,
      visible: true,
      zIndex: 15
    },
    signature: {
      id: 'signature',
      label: 'Authorized Signature',
      type: 'signature',
      x: 460,
      y: 225,
      width: 120,
      height: 52,
      rotation: 0,
      visible: true,
      zIndex: 15
    },
    barcode: {
      id: 'barcode',
      label: 'Barcode',
      type: 'barcode',
      x: 430,
      y: 300,
      width: 150,
      height: 45,
      rotation: 0,
      visible: true,
      zIndex: 15
    }
  }
};

export const DEFAULT_VERTICAL_DESIGN = {
  card: {
    orientation: 'vertical',
    background: '#ffffff',
    headerBg: 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 60%, #1d4ed8 100%)',
    borderRadius: 18,
    borderColor: '#93c5fd',
    borderWidth: 1,
    accentColor: '#38bdf8',
    themeId: 'oxford-blue'
  },
  elements: {
    // Top Header Elements
    collegeEmblem: {
      id: 'collegeEmblem',
      label: 'College Emblem',
      type: 'icon',
      x: 18,
      y: 16,
      width: 38,
      height: 38,
      rotation: 0,
      visible: true,
      zIndex: 20
    },
    collegeName: {
      id: 'collegeName',
      label: 'College Name',
      type: 'text',
      x: 64,
      y: 16,
      width: 260,
      height: 24,
      fontSize: 13,
      fontWeight: '800',
      color: '#ffffff',
      rotation: 0,
      visible: true,
      zIndex: 20,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    collegeTagline: {
      id: 'collegeTagline',
      label: 'Institution Tagline',
      type: 'text',
      x: 64,
      y: 38,
      width: 250,
      height: 16,
      fontSize: 8,
      fontWeight: '600',
      color: '#93c5fd',
      rotation: 0,
      visible: true,
      zIndex: 20,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    smartChip: {
      id: 'smartChip',
      label: 'Smart Chip',
      type: 'object',
      x: 328,
      y: 18,
      width: 34,
      height: 26,
      rotation: 0,
      visible: true,
      zIndex: 20
    },
    idRibbon: {
      id: 'idRibbon',
      label: 'Student ID Ribbon',
      type: 'badge',
      x: 0,
      y: 65,
      width: 380,
      height: 22,
      fontSize: 9,
      fontWeight: '700',
      color: '#ffffff',
      rotation: 0,
      visible: true,
      zIndex: 16
    },

    // Photo Center
    studentPhoto: {
      id: 'studentPhoto',
      label: 'Student Photo',
      type: 'image',
      x: 125,
      y: 98,
      width: 130,
      height: 150,
      rotation: 0,
      visible: true,
      zIndex: 15,
      shape: 'square',
      borderColor: '#38bdf8',
      borderWidth: 2
    },

    // Name & Roll
    studentName: {
      id: 'studentName',
      label: 'Student Name',
      type: 'text',
      x: 20,
      y: 258,
      width: 340,
      height: 28,
      fontSize: 19,
      fontWeight: '900',
      color: '#0f172a',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'center'
    },
    rollNumber: {
      id: 'rollNumber',
      label: 'Roll Number',
      type: 'badge',
      x: 95,
      y: 290,
      width: 190,
      height: 24,
      fontSize: 11,
      fontWeight: '700',
      color: '#1e40af',
      rotation: 0,
      visible: true,
      zIndex: 15
    },
    branch: {
      id: 'branch',
      label: 'Branch / Major',
      type: 'text',
      x: 20,
      y: 322,
      width: 340,
      height: 22,
      fontSize: 12,
      fontWeight: '700',
      color: '#1e3a8a',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'center'
    },
    yearSection: {
      id: 'yearSection',
      label: 'Year & Section',
      type: 'text',
      x: 20,
      y: 346,
      width: 340,
      height: 20,
      fontSize: 11,
      fontWeight: '600',
      color: '#475569',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'center'
    },
    email: {
      id: 'email',
      label: 'Email',
      type: 'text',
      x: 30,
      y: 372,
      width: 320,
      height: 20,
      fontSize: 10,
      fontWeight: '500',
      color: '#334155',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'center'
    },
    phone: {
      id: 'phone',
      label: 'Phone Number',
      type: 'text',
      x: 30,
      y: 394,
      width: 320,
      height: 20,
      fontSize: 10,
      fontWeight: '500',
      color: '#334155',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'center'
    },
    bloodGroup: {
      id: 'bloodGroup',
      label: 'Blood Group',
      type: 'text',
      x: 40,
      y: 420,
      width: 140,
      height: 20,
      fontSize: 10,
      fontWeight: '700',
      color: '#e11d48',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'left'
    },
    dob: {
      id: 'dob',
      label: 'Date of Birth',
      type: 'text',
      x: 200,
      y: 420,
      width: 140,
      height: 20,
      fontSize: 10,
      fontWeight: '500',
      color: '#475569',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'right'
    },
    address: {
      id: 'address',
      label: 'Address',
      type: 'text',
      x: 20,
      y: 444,
      width: 340,
      height: 20,
      fontSize: 9,
      fontWeight: '500',
      color: '#64748b',
      rotation: 0,
      visible: true,
      zIndex: 15,
      fontStyle: 'normal',
      textAlign: 'center'
    },

    // Footer: QR & Signature & Barcode
    qrCode: {
      id: 'qrCode',
      label: 'QR Code',
      type: 'qr',
      x: 40,
      y: 480,
      width: 75,
      height: 75,
      rotation: 0,
      visible: true,
      zIndex: 15
    },
    signature: {
      id: 'signature',
      label: 'Authorized Signature',
      type: 'signature',
      x: 210,
      y: 490,
      width: 130,
      height: 52,
      rotation: 0,
      visible: true,
      zIndex: 15
    },
    barcode: {
      id: 'barcode',
      label: 'Barcode',
      type: 'barcode',
      x: 100,
      y: 562,
      width: 180,
      height: 26,
      rotation: 0,
      visible: false,
      zIndex: 15
    }
  }
};

export function getDefaultDesign(orientation = 'horizontal') {
  return orientation === 'horizontal'
    ? JSON.parse(JSON.stringify(DEFAULT_HORIZONTAL_DESIGN))
    : JSON.parse(JSON.stringify(DEFAULT_VERTICAL_DESIGN));
}
